Feat#10
NullisNot/GoodToKnow-Front pull request #47
Opened 2024-06-12 06:56 UTC by ErikaVorozco

close #feat10
# Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] I have reviewed my code and used the established color palette for the project.
- [ ] I have reviewed my code and used the established font for the project.

2024-06-12 07:14 UTC, maguilerafr requested changes

2024-06-12 07:14 UTC, maguilerafr commented on src/app/components/Pages/information/information.component.html
> -<notnull-footer />
El footer hay que dejarlo en todas las pages

2024-06-12 07:14 UTC, maguilerafr commented on src/app/components/Pages/information/information.component.html
> -<notnull-footer />
También en la de notification

2024-06-12 07:14 UTC, maguilerafr commented on src/app/data/mock/notification.ts
> +        title: "¡ Cambio en la clase del próximo 6 de abril !",
Esto está mal, o sea el título lo deberías de generar en el TS del componente, que partiendo de la fecha que le llega del evento genere ese texto. La fecha le llega en el "startsAt". En el json no le va a llegar ese título si no hay nada que genere ese string como tal.

2024-06-12 07:14 UTC, maguilerafr commented on src/assets/icons/notification.png
Los iconos tenemos una librería que importé el otro día (https://github.com/NullisNot/GoodToKnow-Front/pull/43)

No subas las imágenes e importa los icons desde esta librería.

2024-06-12 07:14 UTC, maguilerafr commented on src/app/components/layout/main/notification-section/notification-section.component.css
> +}
Estaba viendo como te han quedado las notificaciones e intentaría hacer varios retoques:

-Hacerlo más ancho y que estén centrados en la página.
-Poned más separación entre cada uno de los mensajes para que no se lleguen a pisar

2024-06-13 07:37 UTC, ErikaVorozco commented on src/app/components/Pages/information/information.component.html
> -<notnull-footer />
Resuelto!

2024-06-13 07:37 UTC, ErikaVorozco commented on src/assets/icons/notification.png
Solucionado!

2024-06-13 07:38 UTC, ErikaVorozco commented on src/app/components/layout/main/notification-section/notification-section.component.css
> +}
Solucionado!

2024-06-17 16:06 UTC, merged